site_name: TiPS (Snowflake Native App) Documentation

theme:
  name: "material"
  features:
    - content.code.copy
    - navigation.instant
    - navigation.top
  icon:
    repo: fontawesome/brands/github

# repo_url: https://github.com/ProjectiveGroupUK/tips-sf-native-app-docs
# repo_name: ProjectiveGroupUK/tips-sf-native-app-docs

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg  

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - TiPS Conventions: tips_conventions.md
  - Reference Guide: reference.md
  - Demo Videos: demo_video_tips_v1.md

plugins:
    - mkdocs-video:
        is_video: True
        video_autoplay: False  

copyright: Copyright &copy; 2023 ProjectiveGroup UK